### ISSUE TITLE
hgpak

### ISSUE THREAD

**Issue by czdvoika** [cmkushnir/NMSModBuilder#11]
Hi, is there any way to repackage ps4/switch/macos *.pak? It is different from the PC version, it has HGPAK.... in the header

**Comment by czdvoika** [comment]
i try localized games...
(https://drive.google.com/file/d/13V2yjmSQE_CpVL5BMFUKFXyAvdZmjUl0/view?usp=sharing)

**Comment by cmkushnir** [comment]
The app already supports both PSARC and HGPAK (mac) formats.  It will auto-detect the type when reading, and you can choose the format when creating a new pak.  There are 2 query scripts that come with the app that show how to convert a pak from one format to the other, as well as taking an existing pak in one format, making a small change, and repacking in the other format.
However, currently it does not seem like the mac version supports loading mod pak's, and I think the switch version uses a different compression than the mac version.  The app only supports the mac HGPAK format, not the switch HGPAK format which uses the oodle compression.

**Comment by czdvoika** [comment]
tnx for your time
