### ISSUE TITLE
hgpak

### ISSUE THREAD

**Issue by czdvoika** [cmkushnir/NMSModBuilder#13]
hey do you know what these lines are? checksum? tnx :)
https://ibb.co/QCMPnzL

**Comment by cmkushnir** [comment]
Please only use this to report issues with the app.
For general nms modding related questions the best place is the [NMS Modding discord](https://discord.gg/22ZAU9H)

The notes i have for the HGPAK format:
	/// [header]
	///   - "HGPAK" then 3 pad bytes
	///   - uint64 version (?)
	///   - uint64 toc count
	///   - uint64 block count
	///   - bool compressed (?) then 7 pad bytes
	///   - offset to start of block data
	/// [toc] array of toc count items, each with
	///   - 16 bytes MD5 hash (?)
	///   - uint64 offset to start of item in _uncompressed_ data
	///   - uint64 uncompressed length of item
	/// [block sizes] array of block count entries, each with
	///   - uint64 compressed block size
	/// [blocks] 
	///   - first block starts at header offset to start of block data
	///   - read block size[i] bytes, then skip if needed to next 16 byte alignment
	///   - decompress block data and append to total uncompressed data
