### ISSUE TITLE
App has libMBIN.dll 5.1.1.1 but needs 5.2.0.2... but I have libMBIN_v5.02.0-pre2.dll in NMSModBuilder directory...

### ISSUE THREAD

**Issue by Leonixar** [cmkushnir/NMSModBuilder#14]
Well as the tittle says... o.o I let the app download latest library and it still middle fingered at me with this error message... ._.

**Comment by xsSplater** [comment]
I had 2 files like in the image. I deleted the first one and renamed the second one to "libMBIN.dll". Everything worked.
![screenshot_20240731_162048](https://github.com/user-attachments/assets/8bf679a9-da83-467a-91bd-6a8f1eefb53f)

**Comment by Leonixar** [comment]
Oh, that was the trick! :D Thank you! :)
