### ISSUE TITLE
Utility Scripts compile did not generate an Assembly

### ISSUE THREAD

**Issue by OldestChen** [cmkushnir/NMSModBuilder#15]
![image](https://github.com/user-attachments/assets/9bb1f54f-dcbc-4498-8e73-f21fd7a12ca2)

**Comment by cmkushnir** [comment]
When you compile the mod scripts it first tries to compile the scripts in the utility script tab so that they are available for the mod (and query) scripts to use.  Go to the utility tab and click compile there to see the utility script(s) that had error(s).

**Comment by OldestChen** [comment]
> When you compile the mod scripts it first tries to compile the scripts in the utility script tab so that they are available for the mod (and query) scripts to use. Go to the utility tab and click compile there to see the utility script(s) that had error(s).


thanks!
