### ISSUE TITLE
Scripts included with v5.10.0.0 have ambiguous errors

### ISSUE THREAD

**Issue by antisocialian** [cmkushnir/NMSModBuilder#17]
the scripts:
- Add_Decal.cs(274,30)
- Biome.cs(133,37)(139,32)(160,37)(164,32)
- Creature_Pet.cs(15,32)(32,36)(36,39)(46,20)
- Harvester_Rate.cs(20,31)
- Messenger.cs(34,36)(46,20)
- Placeable_Egg_Sequencer.cs(102,30)
- Placeable_Salvage.cs(154,35)
- Plant_Growth.cs(28,35)
- Portal.cs(32,31)
- Refiner.cs(28,33)(44,33)(60,33)
- Scan_Auto.cs(74,36)(86,20)
- Ship.cs(72,35)
- Space_Station.cs(35,41)(36,41)(73,40)(74,50)(91,21)(102,37)

all have error CS0121 popping up with their usage of **_x_.FindFirst** and **_x_.Add** being ambiguous. (_this happens with the current normal and experimental builds of NMS using their respective libmbin.dll builds_)

I'd normally try and understand what it all means, but it's early here and i've not had my coffee yet.

**Comment by cmkushnir** [comment]
i just downloaded the release, unzipped into new folder, tested on both release 5.10 pub and exp.  no errors.  you may have unzipped over an old version and|or mixed old and new scripts.

**Comment by antisocialian** [comment]
i did copy it over the old install. not sure what was different, but it does work now. the old & new scripts are the same too.
