### ISSUE TITLE
Feature Request: Button to open current scripts folder

### ISSUE THREAD

**Issue by Bladehawke** [cmkushnir/NMSModBuilder#5]
Just a button in the toolbar for the Mod Scripts tab to open the current scripts folder in File Explorer

**Comment by cmkushnir** [comment]
Added new Open Folder button to left of Add Script button in all script tabs.
It calls Process.Start("explorer.exe" , ScriptFiles.Path.Full); to open the script folder in a new windows file explorer instance.
Will be in next release.
