### ISSUE TITLE
Feature Request: Windows Store Xbox Game Pass support

### ISSUE THREAD

**Issue by Joshaze** [cmkushnir/NMSModBuilder#6]
Do you have any plans or would it be possible to add support for the Windows Store | Xbox Game Pass version of NMS?

**Comment by cmkushnir** [comment]
I don't know what would be required.  Either the game files are user accessible on one of the drives, in which case NMSMB will work if you point it to the correct folder, or they are embedded in some kind of virtual drive that the xbox app on the pc uses to run the app, in which case probably not.
If you can find them as user accessible files somewhere and get NMSMB to run by pointing it to that folder then I'll add the code to find that folder and add an icon to the toolbar.

**Comment by Joshaze** [comment]
The XBox application now allows you to convert some games from the standard encrypted installation to a modifiable standard installation by enabling Advanced management features found in the manage menu.

![image](https://user-images.githubusercontent.com/63926402/183262618-8a548b22-42b4-482f-a03d-1656415e9818.png)

![image](https://user-images.githubusercontent.com/63926402/183262654-f06a9d06-a0df-48f0-a89a-afc772a1c755.png)

Enabling the Advanced management feature moves the installation from the X:/WindowsApps folder to an X:/XboxGames folder which has more relaxed permissions.

NMSModBuilder appears to recognize the installation folder and the version of NMS:
![image](https://user-images.githubusercontent.com/63926402/183262857-de5bb8d2-ea1e-459b-9f5c-f330d63a5031.png)

NMSModBuilder appears to be trying to access NMS.exe and reports the following Error:

![image](https://user-images.githubusercontent.com/63926402/183262944-8a80d070-b4ca-4e60-b671-2b302a780e0b.png)

Text Here:
[02:04:21.485] System.UnauthorizedAccessException: Access to the path 'C:\XboxGames\No Man's Sky\Content\Binaries\NMS.exe' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at cmk.IO.File.WaitOpen(FileMode MODE, FileAccess ACCESS, FileShare SHARE, TimeSpan TIMEOUT, CancellationToken CANCEL) in D:\dev\prj\cmk\Game\NMS\Common\Utility\IO.Item.cs:line 211

Here are the advanced permissions for the NMS executable:
![image](https://user-images.githubusercontent.com/63926402/183263036-de6f2c9e-bf56-42b8-bccd-97894ec12381.png)

I'd be happy to try any suggestions you have.

Also, in case it's helpful both the AMUMSS LUA modding tool (https://github.com/HolterPhylo/AMUMSS) and the NomNom save game editor (https://github.com/cengelha/NomNom) work with the Windows Store / Xbox Game Pass version of NMS. Perhaps something could be gleamed from their projects as to how they access the files?

Thank you for taking the time to respond and let me know if I can help. I appreciate you!

-Josh

**Comment by Joshaze** [comment]
I did try running NMSModBuilder  as a standard user, Adminstrator, SYSTEM, and as TrustedInstaller but all resulted in the same error.

I have not modified the permissions on the executable or any of the directories but I'm willing to try anything. I can always delete and redownload the game if needed.

**Comment by cmkushnir** [comment]
1) If you are going to use a game in a non-detected location you may as well use the command-line option e.g
x:/nmsmb/cmkNMSModBuilder.exe -p"C:\XboxGames\No Man's Sky\Content"
You may also want to add -lp to load that -p path when the app starts, possibly -r3.98 to force the game release, possibly -v3.98.0.3 to force the libmbin version to use.  Specifying the game release will cause the app to use it, but it will still try to read the build date from nms.exe, so nms.exe needs read permission.  I'm not sure how best to do that for the xbox games.  It may be worth trying, hopefully it will work but you will just see the error and an invalid date.
2) The Select Game Location dialog is not detecting the correct release, it is showing the latest release it knows about.  It determines the release from the date, which it couldn't get.
3) AMUMSS and other tools don't try to read nms.exe, so they won't get the error.

So I'd start by trying 1), specify -p and -r command-line param and see what happens.
I'd verify that it's able to read the game pak files, just look at the language or substance tab to see if they have any info after loading.  The loading messages should also make it clear if there were errors.
Finally I'd look at ways of getting read permission on nms.exe to get rid of the error and get a valid build date.

For reference you can look at the PEBuildDate method in https://github.com/cmkushnir/NMSModBuilder/blob/main/Common/Utility/IO.Item.cs to see how it's trying to read the build date from nms.exe.

**Comment by Joshaze** [comment]
Unfortunately, any variation or combination of the variables that includes that path fails to launch the program. I get the splash screen but then it closes and returns to the command prompt with no error or other message.

non-elevated command prompt:
![image](https://user-images.githubusercontent.com/63926402/183291402-cf579f4c-1a8b-47ac-895d-0d97de63202d.png)

elevated command prompt:
![image](https://user-images.githubusercontent.com/63926402/183291723-6947d6af-bd63-4fe9-a591-0a7aa17db561.png)

elevated command prompt as SYSTEM user:
![image](https://user-images.githubusercontent.com/63926402/183291908-b68a1376-5b9e-433c-ade7-930caa8211ad.png)

I also tried running as TrustedInstaller but got the same results as the SYSTEM user.

The first command "cmkNMSModBuilder.exe -r3.98 -v3.98.0.3 -no_mbin_cache" successfully launches the GUI but fails with the same Access Denied when I browse to the "C:\XboxGames\No Man's Sky\Content" folder.

**Comment by cmkushnir** [comment]
-r and -v are ignored if there  is no -p.  In all cases the app (gui) should still open, the issue should only be logged errors once you try to load the game instance.  If the gui isn't opening or is closing right away there is another issue.

The only command-line I'd try is:
E:\Downloads\Games\No Man's Sky\NMSModBuilder>cmkNMSModBuilder.exe -p"C:\XboxGames\No Man's Sky\Content"
With that the app should start, display the gui and you should get a red|yellow|green face icon on the toolbar that represents that path if it validates the path.

The code does the following:
```
...
				else if( arg[0] == '-' ) {
					switch( arg[1] ) {
						case 'p':  // path of game instance, e.g. -p"g:/games/archive/nms/1"
							game_path = arg.Substring(2).Trim('\"');
							break;
...
			if( !game_path.IsNullOrEmpty() ) {
				if( !NMS.Game.Location.Data.IsValidGamePath(game_path) ) {
					Log.Default.AddWarning($"-p\"{game_path}\" invalid game path (missing PCBANKS or NMS.exe)");
				}
				else {
					NMS.Game.Release release = null;
					if( !game_release .IsNullOrZero() ) release = NMS.Game.Releases.FindGameVersion(game_release);
					if( !mbinc_version.IsNullOrZero() ) release = NMS.Game.Releases.FindMbincVersion(mbinc_version);
					if( release == null ) {
						var built = NMS.Game.Location.Data.PEBuildDate(game_path);
						release = NMS.Game.Releases.FindBuilt(built);
					}
					if( release == null ) {
						Log.Default.AddWarning($"-p\"{game_path}\" valid path, but unable to determine release");
					}
					else {
						NMS.Game.Location.Data.Custom.Add(new(game_path, release));
					}
				}
			}
```
So I'd expect your -p option to log the "... valid path, but unable to determine release" error.

Just to verify, can you dump the .NET 5 and .NET 6 info for what you have installed e.g. I get the following:
>dotnet --info
.NET SDKs installed:
  5.0.303 [c:\program files\dotnet\sdk]
  5.0.404 [c:\program files\dotnet\sdk]
  5.0.408 [c:\program files\dotnet\sdk]
  6.0.105 [c:\program files\dotnet\sdk]
  6.0.300 [c:\program files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.NETCore.App 5.0.9 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.9 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by cmkushnir** [comment]
An extreme thing to try would be to copy the files from C:\XboxGames\No Man's Sky\Content into another folder and try to get nmsmb to use it.  When it builds a mod pak you can select where to save it, by default it will want to save in the game folder you loaded, but you could redirect to save in C:\XboxGames\No Man's Sky\Content\GAMEDATA\PCBANKS\MODS\ instead.

**Comment by Joshaze** [comment]
Running "cmkNMSModBuilder.exe -p"C:\XboxGames\No Man's Sky\Content"" results in the Splashscreen displaying and then the window goes away and returns to the command prompt.

![image](https://user-images.githubusercontent.com/63926402/183317052-e0b1fb1f-c2a4-4b39-82ec-9c7836db8e92.png)

**Comment by Joshaze** [comment]
It will not let me copy the NMS.exe file out of its default location. I'll try dumping it with UWPDumper <https://github.com/Wunkolo/UWPDumper>.

Also, I tried copying all but the NMS.exe and pointed cmkNMSModBuilder to that folder but they all do the same thing. The splashscreen displays and then closes and returns to the command prompt.
![image](https://user-images.githubusercontent.com/63926402/183317562-635e6ed6-725a-4907-b1ea-a2d6249eea62.png)

**Comment by Joshaze** [comment]
I pointed cmkNMSModBuilder to the UWPDumped content and that looks to have worked. Now if only that could be done to the original location so I don't have to duplicate the storage space.
![image](https://user-images.githubusercontent.com/63926402/183317898-e50b2b29-1e70-4080-8066-e1ea66b3ff8c.png)

**Comment by cmkushnir** [comment]
Ok, the good part is that nmsmb and it's dep's are working correctly.  The fact that the -p option doesn't allow the app to start may be due to it throwing an exception when it tries to check if the folder even exists i.e. it's not even getting to the point of trying to read nms.exe, it's the whole install folder structure that fails permission checks.
I'll google later to see if there's anything to get around the perm issue e.g. requesting elevated priv in app or something.

**Comment by cmkushnir** [comment]
Have you tried doing things like this:
https://answers.microsoft.com/en-us/windows/forum/all/not-permissions-in-windowsapps-from-game-pass-pc/ad72b6de-a977-4038-8417-ffe65d4abb92
https://www.reddit.com/r/XboxGamePass/comments/qxkvm5/xbox_pc_insiders_can_now_enable_advanced_installs/

**Comment by cmkushnir** [comment]
Game Pass support added to 3.99.1.4.
Requires NMS to be moved to XboxGames folder using Xbox app, however app will still access via link created in orig install location, as that's how the API reports the path.  Does not require any changes to file or folder permissions.
