### ISSUE TITLE
Version list appears to be listing the wrong release name

### ISSUE THREAD

**Issue by Joshaze** [cmkushnir/NMSModBuilder#7]
Just noticed this morning that releases 3.96, 3.97, and 3.98 were labeled Leviathan however I think they should be named Endurance (per the official NMS release log https://www.nomanssky.com/release-log/).

Is 3.98.1 a test build? I don't see it in the official log.

![image](https://user-images.githubusercontent.com/63926402/183411039-df36fcdf-9c49-41b3-abb9-6960746beb83.png)

**Comment by cmkushnir** [comment]
When the app starts it loads the local cmkNMSReleases.txt file into memory, it then loads the same file from GitHub (https://github.com/cmkushnir/NMSModBuilder/blob/main/Common/cmkNMSReleases.txt) and adds any newer entries to the in-memory list.  That merged list is what should be displayed.
The GitHub list has correct entries, however it seems I messed them up (copy & paste error) when I added them to the list that gets shipped w/ the last update, I'll fix for next update.  If you want to fix now just delete or correct those entries in your local file.
3.98.1 is the latest experimental.  As an experimental it has no official number from HG, so I usually just increment the 3rd part of the version for each experimental until the next release, then go back and fix-up as needed.
