### ISSUE TITLE
Feature Request: Next/prev diff

### ISSUE THREAD

**Issue by raiddn** [cmkushnir/NMSModBuilder#8]
Not sure if I just didn't see it, or if already requested.

Would love a goto next/previous diff ala Winmerge. They default the keybinds to Alt+Up/Down.

Much appreciated!

**Comment by cmkushnir** [comment]
It's not currently present, but I'll look into adding it.  I've already added Alt-Up, Left, Right, Down to scroll to first, prev, next, last search match in a text viewer, and Ctrl and Shift modifiers are already used.

**Comment by cmkushnir** [comment]
I've updated the code, will be in next release:
Alt-Up, Down, Left, Right will scroll to First, Last, Prev, Next search match.
Alt-W, S, A, D will scroll to First, Last, Prev, Next diff result when viewing text diffs.
I may change the bindings before release, the actual bindings will be in the release notes.

**Comment by cmkushnir** [comment]
Available in release 4.22.0.0.
